# Generated by Django 6.0.4 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_pageview_blogpost_likes_blogpost_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cta',
            field=models.CharField(blank=True, help_text='Short call-to-action, e.g. "Book a free consultation today!"', max_length=100),
        ),
    ]
