# Generated by Django 6.0.4 on 2026-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Service Business', max_length=200)),
                ('tagline', models.CharField(blank=True, default='Quality Expert Services', max_length=300)),
                ('hero_subtext', models.TextField(blank=True, default='From plumbing to electrical work, teaching to construction showcasing skilled professionals and their outstanding work')),
                ('logo', models.ImageField(blank=True, help_text='Site logo (recommended: transparent PNG)', null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab icon (32x32 PNG)', null=True, upload_to='settings/')),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('primary_color', models.CharField(default='#e94560', help_text='Main brand color (hex)', max_length=20)),
                ('primary_dark', models.CharField(default='#d63a54', help_text='Darker shade for hover', max_length=20)),
                ('secondary_color', models.CharField(default='#16213e', help_text='Secondary brand color', max_length=20)),
                ('dark_color', models.CharField(default='#1a1a2e', help_text='Darkest color (navy/black)', max_length=20)),
                ('light_color', models.CharField(default='#f8f9fa', help_text='Light background color', max_length=20)),
                ('text_color', models.CharField(default='#343a40', help_text='Primary text color', max_length=20)),
                ('navbar_position', models.CharField(choices=[('top', 'Top (Default)'), ('bottom', 'Bottom Fixed'), ('left', 'Vertical Left')], default='top', max_length=10)),
                ('navbar_width', models.CharField(choices=[('full', 'Full Width (100%)'), ('contained', 'Contained (90%)')], default='full', max_length=20)),
                ('border_radius', models.CharField(choices=[('sharp', 'Sharp (0px)'), ('moderate', 'Moderate (6px)'), ('smooth', 'Smooth (12px)'), ('extra', 'Extra Round (20px)')], default='smooth', max_length=10)),
                ('footer_content', models.TextField(blank=True, default='Empowering skilled professionals to showcase their work and grow their business.')),
                ('footer_links', models.TextField(blank=True, default='[{"title": "Home", "url": "/"}, {"title": "Blog", "url": "/blog/"}, {"title": "Portfolio", "url": "/portfolio/"}]', help_text='JSON array of links')),
                ('social_links', models.TextField(blank=True, default='{"facebook": "", "instagram": "", "twitter": "", "linkedin": ""}', help_text='JSON object of social URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
