# Generated by Django 6.0.4 on 2026-05-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(blank=True, help_text='Service interested in', max_length=100)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, default='contact_form', max_length=50)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL or direct video link', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lead_contact_info',
            field=models.TextField(blank=True, default='We respond within 24 hours. Fast, reliable service guaranteed.', help_text='Text shown near contact/lead forms'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lead_cta_text',
            field=models.CharField(blank=True, default='Get a Free Quote Today', help_text='Lead capture CTA text', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(help_text='Cover image', upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cta',
            field=models.CharField(blank=True, help_text='Short call-to-action', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='blog.portfolio')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
