from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.custom_login, name='login'),
    path('register/', views.custom_register, name='register'),
    path('logout/', views.custom_logout, name='logout'),
    path('profile/', views.user_profile_view, name='user_profile'),
    path('lead/', views.lead_submit, name='lead_submit'),
    path('newsletter/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/new/', views.blog_create, name='blog_create'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('blog/<slug:slug>/edit/', views.blog_update, name='blog_update'),
    path('blog/<slug:slug>/delete/', views.blog_delete, name='blog_delete'),
    path('blog/<slug:slug>/like/', views.blog_like, name='blog_like'),
    path('blog/<slug:slug>/share/', views.blog_share, name='blog_share'),
    path('portfolio/', views.portfolio_list, name='portfolio_list'),
    path('portfolio/new/', views.portfolio_create, name='portfolio_create'),
    path('portfolio/<slug:slug>/', views.portfolio_detail, name='portfolio_detail'),
    path('portfolio/<slug:slug>/edit/', views.portfolio_update, name='portfolio_update'),
    path('portfolio/<slug:slug>/delete/', views.portfolio_delete, name='portfolio_delete'),
    path('portfolio/<slug:slug>/share/', views.portfolio_share, name='portfolio_share'),
    path('portfolio/image/<int:pk>/delete/', views.portfolio_image_delete, name='portfolio_image_delete'),
    path('admin-dashboard/', views.analytics_dashboard, name='analytics'),
    path('admin-dashboard/profile/', views.profile_view, name='profile_view'),
    path('admin-dashboard/categories/', views.category_list, name='category_list'),
    path('admin-dashboard/categories/new/', views.category_create, name='category_create'),
    path('admin-dashboard/categories/<slug:slug>/edit/', views.category_update, name='category_update'),
    path('admin-dashboard/categories/<slug:slug>/delete/', views.category_delete, name='category_delete'),
    path('admin-dashboard/comments/', views.comment_list, name='comment_list'),
    path('admin-dashboard/comments/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('admin-dashboard/comments/<int:pk>/delete/', views.comment_delete, name='comment_delete'),
    path('admin-dashboard/site-settings/', views.site_settings_view, name='site_settings'),
    path('admin-dashboard/leads/', views.leads_list, name='leads_list'),
    path('admin-dashboard/leads/<int:pk>/contacted/', views.lead_mark_contacted, name='lead_mark_contacted'),
    path('admin-dashboard/leads/<int:pk>/delete/', views.lead_delete, name='lead_delete'),
]
